### ISSUE TITLE
ユーザー情報変更の Name (English) が入力できない

### ISSUE THREAD

**Issue by metalefty** [homenoc/dsbd-web#100]
各種手続き→ユーザー情報変更→DETAIL→ユーザー情報の変更

仕様がわからないのですが、Name (English) にフォーカスを当てても入力ができず、何らかの自動入力も行われません。

よって、ここを空のまま更新することしかできず結果として以下のようなエラーになります。

<img width="944" alt="スクリーンショット 2021-08-10 18 05 53" src="https://user-images.githubusercontent.com/941609/128839974-b5950433-0eed-4777-becb-813adb422b85.png">

**Comment by metalefty** [comment]
このあたり、他にもバグの予感がしたのでユーザーの削除をしてみたところ、404でこちらもエラーとなりました。
スクリーンショットではフォームに何も入力していませんが、メールアドレスを入力した状態でも同様です。


<img width="888" alt="スクリーンショット 2021-08-10 18 21 14" src="https://user-images.githubusercontent.com/941609/128842237-02df0832-20b9-4878-b8b8-332a1b462a05.png">

<img width="444" alt="スクリーンショット 2021-08-10 18 32 12" src="https://user-images.githubusercontent.com/941609/128843921-ca096a09-f39e-4bf3-870a-8efd1455027a.png">

現在のものとは別のメールアドレスを入力して、メールアドレスを変更しようとしたところ、こちらも401でエラーとなりました。

<img width="425" alt="スクリーンショット 2021-08-10 18 34 12" src="https://user-images.githubusercontent.com/941609/128844251-4cf473b8-b0d9-44b8-b750-75d0400473a3.png">

**Comment by yoneyan** [comment]
報告いただきまして、ありがとうございます！
こちらで確認いたしますので、少々お待ちください。

**Comment by yoneyan** [comment]
[fix] 409ab08d81239b6cb8a801b829707adb255c3e4e

**Comment by yoneyan** [comment]
確認が完了し、修正いたしましたのでご報告させていただきます。
- 409ab08
- 4255f59

**Comment by metalefty** [comment]
修正されていることを確認しました。
