### ISSUE TITLE
registration/network 広報経路が1つしか選べない

### ISSUE THREAD

**Issue by kt-yamaguchi** [homenoc/dsbd-web#11]
デュアルスタックの場合はIPv4で1個、IPv6で1個を選択する必要がある。
![image](https://user-images.githubusercontent.com/19766266/97329772-c602fb80-18ba-11eb-8bd1-e65bb621d75a.png)

**Comment by yoneyan** [comment]
e274dcd4c2749f0acfba793e0bff2da60975bdfe にて修正
