### ISSUE TITLE
registration/network PIアドレスの利用希望欄

### ISSUE THREAD

**Issue by kt-yamaguchi** [homenoc/dsbd-web#12]
「利用を希望する」にチェックを入れると、AS番号の入力欄が表示される。
チェックを入れない状態で、「1セグメントずつ入力してください」のメッセージが表示されている。

※ PIアドレスを持ち込み人が、必ずAS番号を持っているとは限らない（HOMENOCの代理広報のケースもある）ので、AS番号を書かせる項目は別に存在すべき。

**Comment by yoneyan** [comment]
e274dcd4c2749f0acfba793e0bff2da60975bdfe にて修正
