### ISSUE TITLE
接続情報の追加ができない

### ISSUE THREAD

**Issue by bgp4plus** [homenoc/dsbd-web#147]

**Comment by bgp4plus** [comment]
<img width="2107" alt="image" src="https://user-images.githubusercontent.com/44109903/195977665-1eda52ba-853d-48bb-8000-c5dfabe263f8.png">

**Comment by yoneyan** [comment]
ServiceCodeが200(L2)で起きていた本事象は e768c62cea5e33c5e5529fe04fab0d133023cd4d にて解決済み
