### ISSUE TITLE
チケット作成画面にmarkdown可という記載を追加する

### ISSUE THREAD

**Issue by symysak** [homenoc/dsbd-web#164]
チャット画面には"このチャットはMarkdownに準拠しております。"と表記がありますが、
チケット作成画面にも同じような文言を追加したほうが良いと思います。

修正が必要だと思われる箇所: 
https://github.com/homenoc/dsbd-web/blob/develop/src/pages/Support/SupportAddDialog.tsx

必要無いと判断された場合は、お手数ですがクローズをお願いいたします。

**Comment by yoneyan** [comment]
@symysak 
あざます！
よろしければ、文言を追加してpull request投げてもらえると非常に助かりまする

**Comment by symysak** [comment]
了解です〜！
