### ISSUE TITLE
Verify画面に、入力した内容を表示した方が良い

### ISSUE THREAD

**Issue by kt-yamaguchi** [homenoc/dsbd-web#5]
以下の画面に、全画面で入力した内容を表示して「この内容で登録を行うけど良いか」の確認を促した方が良い。
![image](https://user-images.githubusercontent.com/19766266/97100288-626ba900-16d5-11eb-9e5a-1c3a287c91f6.png)

**Comment by yoneyan** [comment]
![Screenshot from 2020-10-30 20-44-12](https://user-images.githubusercontent.com/40447529/97701414-b66cf800-1af0-11eb-949e-ed11fc1539f1.png)

f529551b7fee4ef061940b362358375e7cb8e204 機能追加完了
