### ISSUE TITLE
自動ログアウトに関する不具合

### ISSUE THREAD

**Issue by kt-yamaguchi** [homenoc/dsbd-web#8]
ログイン後、一定時間何も操作をせずに放置したあと、手動でトップページに戻りログイン／ログアウトが必要になる。
F5キーで画面更新すると、ログインしたままのようなダッシュボード画面が表示されているが、実際に入力などをするとエラーになる。

**Comment by yoneyan** [comment]
a9214f72f702e4b32f40db443f55d4f8fee103b9 にて実装

**Comment by yoneyan** [comment]
自動ログアウト処理が出来ておらず、操作不能になることがある

**Comment by yoneyan** [comment]
すでに修正済み
