### ISSUE TITLE
「収容NOC希望なし」のユーザを開通しても「希望無し」と表示されている

### ISSUE THREAD

**Issue by kt-yamaguchi** [homenoc/dsbd-web#88]
「収容NOC希望なし」のユーザをNOC指定して追加しても以下の表示となる
![image](https://user-images.githubusercontent.com/19766266/114276526-f2be6000-9a61-11eb-90fb-897862858122.png)

**Comment by yoneyan** [comment]
同様のバグ又は新バグが発生している可能性があるため保留とします

**Comment by yoneyan** [comment]
旧システムのバグのため、一旦Closeします。
