### ISSUE TITLE
ユーザ情報の「住所」に組織名が入ってしまう

### ISSUE THREAD

**Issue by kt-yamaguchi** [homenoc/dsbd-web#9]
以下のように、組織名の「自宅ラック」が、住所の部分に入っています。
![image](https://user-images.githubusercontent.com/19766266/97104757-b4bec100-16f9-11eb-9a5d-5b02716b9aab.png)

**Comment by yoneyan** [comment]
3f8e0479e4774e27de7de58e1e560fdd39b0bc63 にて解決
