### ISSUE TITLE
Group情報の申請(初期申請)にて文字数制限のチェック?が通らない

### ISSUE THREAD

**Issue by masebb** [homenoc/dsbd-web#97]
## 起こっていること
HomeNOCの利用を開始しようとアカウントを登録して全ての必須項目を埋めて初期申請をしようとすると下の画像のように「[項目1,項目2,項目3,項目4]質問欄の文字数が足りません。」と必ずエラー表示が出る
![スクリーンショット 2021-07-29 1 57 05](https://user-images.githubusercontent.com/30523995/127364642-76bc1866-c3b4-4258-a081-08940a64d405.png)
項目1、3、4は文字数制限はないと思われますし、項目2の文字数制限300字以上は突破(スペース込みで337字)した状態でもこの表示が出ます
## 環境
MacOS Catalina 11.1上にて
 - FireFox 89.0.2（64ビット）
 - Chrome 92.0.4515.107（Official Build） （x86_64）
 
どちらの環境でもバグを確認

**Comment by yoneyan** [comment]
報告いただきまして、ありがとうございます！
確認後、修正いたします。

**Comment by masebb** [comment]
環境について書き忘れていたので追記しました〜

**Comment by yoneyan** [comment]
確認したところ、質問項目のチェック機構が正常に働いていなかったことが原因でした。

**Comment by yoneyan** [comment]
8c8910d にて修正しました。

**Comment by yoneyan** [comment]
3b96862 にてquestionデータだけが抜ける問題を修正

**Comment by yoneyan** [comment]
今回はご指摘いただきありがとうございました！
また、こちらでも検証し本番環境にて適用しました。

**Comment by masebb** [comment]
こちらこそご対応ありがとうございました～
無事に申請のほうできるようになりましたので申請をさせていただきました！
